### ISSUE TITLE
wrong url in "how-to"

### ISSUE THREAD

**Issue by MaddestHatter** [19morpheus80/helper#1]
in the how to is written "git clone https://19morpehus80/helper"
shouldn´t it be "git clone https://github.com/19morpheus80/helper.git "  ?

**Comment by 19morpheus80** [comment]
just seen this; which file is that in?

**Comment by MaddestHatter** [comment]
hey morpheus , uhh no sure if still needed but i thing in https://github.com/19morpheus80/helper/blob/master/helper.sh around Line 121 ?

**Comment by MaddestHatter** [comment]
Hey Morpheus , i think its done , this was here https://github.com/19morpheus80/helper/commit/8e32c0199290b9fef4d19aaeb0836b0251bec964 ...
